#!/usr/bin/env python3
"""Generate bounded implementation-support projections from pinned playbooks."""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any

EXPECTED_ROLES = ("research", "plan", "write-code", "review")
MANIFEST_NAME = "support-projections.json"
GENERATED_NOTICE = (
    "<!-- GENERATED by scripts/generate_support_projections.py from "
    "support-projections.json; do not edit directly. -->"
)


class ProjectionError(ValueError):
    """Raised when the projection contract or a pinned source is invalid."""


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_manifest(path: Path) -> dict[str, Any]:
    try:
        manifest = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ProjectionError(f"cannot read manifest {path}: {exc}") from exc

    if manifest.get("schema_version") != 1:
        raise ProjectionError("manifest schema_version must be 1")
    common = manifest.get("common")
    projections = manifest.get("projections")
    if not isinstance(common, dict) or not isinstance(projections, list):
        raise ProjectionError("manifest requires common object and projections array")
    for key in ("required_inputs", "required_returns", "forbidden"):
        if not isinstance(common.get(key), list) or not common[key]:
            raise ProjectionError(f"common.{key} must be a non-empty array")

    roles = tuple(item.get("role") for item in projections if isinstance(item, dict))
    if roles != EXPECTED_ROLES:
        raise ProjectionError(
            f"projection roles must be exactly {EXPECTED_ROLES}, found {roles}"
        )
    for item in projections:
        for key in (
            "source",
            "source_sha256",
            "output",
            "purpose",
            "instructions",
        ):
            if key not in item:
                raise ProjectionError(f"{item['role']} projection missing {key}")
        if (
            len(item["source_sha256"]) != 64
            or any(char not in "0123456789abcdef" for char in item["source_sha256"])
        ):
            raise ProjectionError(f"{item['role']} source_sha256 is not canonical")
        if not isinstance(item["instructions"], list) or not item["instructions"]:
            raise ProjectionError(f"{item['role']} instructions must be non-empty")
    return manifest


def verify_sources(manifest: dict[str, Any], repo_root: Path) -> None:
    for item in manifest["projections"]:
        source = repo_root / item["source"]
        if not source.is_file():
            raise ProjectionError(f"{item['role']} source does not exist: {source}")
        actual = sha256_file(source)
        if actual != item["source_sha256"]:
            raise ProjectionError(
                f"{item['role']} source drift: expected {item['source_sha256']}, "
                f"found {actual}; review the source change before repinning"
            )


def bullet_lines(values: list[str]) -> list[str]:
    return [f"- {value}" for value in values]


def render_projection(item: dict[str, Any], common: dict[str, Any]) -> str:
    title = item["role"].replace("-", " ").title()
    lines = [
        GENERATED_NOTICE,
        "",
        f"# {title} Support Projection",
        "",
        f"Source: `{item['source']}`",
        f"Pinned SHA-256: `{item['source_sha256']}`",
        "",
        "## Purpose",
        "",
        item["purpose"],
        "",
        "This is a bounded capability projection. The prototype-driven implementation controller",
        "retains lifecycle ownership.",
        "",
        "## Required input",
        "",
        *bullet_lines(common["required_inputs"]),
        "",
        "If any input is missing, return that as unresolved uncertainty; do not broaden the task.",
        "",
        "## Apply",
        "",
        *[f"{index}. {value}" for index, value in enumerate(item["instructions"], 1)],
        "",
        "## Required return",
        "",
        *bullet_lines(common["required_returns"]),
        "",
        "## Forbidden",
        "",
        *bullet_lines(common["forbidden"]),
        "",
    ]
    return "\n".join(lines)


def expected_outputs(
    manifest: dict[str, Any], output_dir: Path
) -> dict[Path, str]:
    common = manifest["common"]
    return {
        output_dir / item["output"]: render_projection(item, common)
        for item in manifest["projections"]
    }


def write_or_check(outputs: dict[Path, str], check: bool) -> list[str]:
    problems: list[str] = []
    for path, expected in outputs.items():
        if check:
            if not path.is_file():
                problems.append(f"missing generated projection: {path}")
            elif path.read_text(encoding="utf-8") != expected:
                problems.append(f"stale generated projection: {path}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(expected, encoding="utf-8")
    return problems


def parse_args(argv: list[str]) -> argparse.Namespace:
    skill_root = Path(__file__).resolve().parents[1]
    repo_root = skill_root.parents[1]
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    parser.add_argument("--repo-root", type=Path, default=repo_root)
    parser.add_argument("--manifest", type=Path, default=skill_root / MANIFEST_NAME)
    parser.add_argument(
        "--output-dir", type=Path, default=skill_root / "references"
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv or sys.argv[1:])
    try:
        manifest = load_manifest(args.manifest)
        verify_sources(manifest, args.repo_root.resolve())
        problems = write_or_check(
            expected_outputs(manifest, args.output_dir.resolve()), args.check
        )
    except ProjectionError as exc:
        print(f"support-projections: {exc}", file=sys.stderr)
        return 2
    if problems:
        for problem in problems:
            print(f"support-projections: {problem}", file=sys.stderr)
        return 1
    verb = "verified" if args.check else "generated"
    print(f"support-projections: {verb} {len(manifest['projections'])} projections")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
